// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/background.js"
    | "/content-scripts/content.js"
    | "/dashboard.html"
    | "/icons/apple-touch-icon-114x114.png"
    | "/icons/apple-touch-icon-120x120.png"
    | "/icons/apple-touch-icon-144x144.png"
    | "/icons/apple-touch-icon-152x152.png"
    | "/icons/apple-touch-icon-57x57.png"
    | "/icons/apple-touch-icon-60x60.png"
    | "/icons/apple-touch-icon-72x72.png"
    | "/icons/apple-touch-icon-76x76.png"
    | "/icons/favicon-128.png"
    | "/icons/favicon-16x16.png"
    | "/icons/favicon-196x196.png"
    | "/icons/favicon-32x32.png"
    | "/icons/favicon-96x96.png"
    | "/icons/favicon.ico"
    | "/icons/favicon.svg"
    | "/icons/icon.png"
    | "/icons/icon.svg"
    | "/icons/mstile-144x144.png"
    | "/icons/mstile-150x150.png"
    | "/icons/mstile-310x150.png"
    | "/icons/mstile-310x310.png"
    | "/icons/mstile-70x70.png"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime extends Runtime.Static {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
